### ISSUE TITLE
Label for dwarf stars and extrasolar planets are offset from their groups

### ISSUE THREAD

**Issue by amaurea** [paperscape/paperscape-mapclient#6]
Several labels in the astrophysics group are offset from the sub-groups they refer to. [This screenshot](http://folk.uio.no/sigurdkn/paperscape_label_offset.png) illustrates the effect. This was taken using Firefox 59 nightly, but it looks the same in Chromium. As you can see, there are two distinct groupings in the right part of this image, corresponding to dwarf stars and extrasolar planets. But the corresponding labels are offset by so much that the closest label to the extrasolar planet group is actually the dwarf star one, and the extrasolar planet label is lost in the void below.

**Comment by dpgeorge** [comment]
Thanks for the report!  This issue arises because the locations of these high-level labels was determined manually by eye a long time ago (around 4 years ago) and since then the graph has gradually grown and changed due to the addition of new papers.  In https://github.com/paperscape/paperscape-backend/commit/bcc4da8cb46972fd4af942e11822d9e46bc450b9 I updated the code to allow to link a region label to a specific paper, in the hope that that will be a more robust way to keep these labels over the same region.  The map itself should be updated tomorrow.

**Comment by dpgeorge** [comment]
This is indeed fixed in the latest map.

**Comment by amaurea** [comment]
> This is indeed fixed in the latest map.

Thanks, I can confirm that.
